### PR TITLE
Presentation mode

### PR DESCRIPTION
**Pull request by vidbina**
Better buttons since @andi-tmh is running into a lot of issues while demoing runway setups on a beamer. The buttons should make the experience less painful, furthermore @andi-tmh propsed a details button which hides the the tabs containing the state tables.

### CODE REVIEW

**Comment by ongardie-sfdc** [comment]
Thanks, @vidbina. I do like the new buttons.

Do you mind removing the old, now hidden, checkbox? I don't think it's needed in many places.

Before I can merge this and your other PR (#13), we need a CLA (Contributor's License Agreement) from you or The Mobility House, as appropriate. You can find the CLA [here](https://github.com/forcedotcom/idecore/raw/master/SFDC_CLA.pdf); please send the completed form to osscore@salesforce.com. You only need to do this once; it'll be valid for any Salesforce project. Feel free to email that list (which I'm on) with questions. Sorry for the hurdle, but I look forward to merging this and continuing to collaborate on Runway.

**Comment by ongardie-sfdc** [comment]
@vidbina got your CLA, thanks. Could you remove that hidden checkbox?

**Comment by vidbina** [comment]
On it

**Comment by ongardie-sfdc** [comment]
Merged, thanks @vidbina!

**Pull request merged**
